### ISSUE TITLE
DraggableData

### ISSUE THREAD

**Issue by jiangqi511** [marshal-zheng/vue-draggable#1]
How do I change the x and y in the DraggableData, when I change them at the end of a drag, it doesn't work on the next round of dragg.

**Comment by marshal-zheng** [comment]
Hi, the component doesn’t automatically track changes in x and y between drags if they’re not updated in a reactive way. 

Here’s how you can update x and y using stopFn or dragFn. Please refer to the method's TypeScript definitions in DraggableEventHandler for details. Here's an example using stopFn:

const position = reactive({ x: 0, y: 0 });

const handleStop = (event, data) => {
  Object.assign(position, { x: data.x, y: data.y });
};
